### ISSUE TITLE
ImportError "No module named 'src'"

### ISSUE THREAD

**Issue by laedit** [r3c/creep#1]
Thanks a lot for this app, it seems to be doing exactly what I want 😃 

But every time I call `creep` I got the following error:

``` bash
D:\Prog\Github\ReadingList\site>creep
Traceback (most recent call last):
  File "c:\users\man-p\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\man-p\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\man-p\AppData\Local\Programs\Python\Python35\Scripts\creep.exe\__main__.py", line 5, in <module>
  File "c:\users\man-p\appdata\local\programs\python\python35\lib\site-packages\creep\creep.py", line 6, in <module>
    import src
ImportError: No module named 'src'
```

I used `pip` for install and running it on Windows 10 with Python 3.5.2.
And in the `creep` installation folder I have the `src` folder.

Am I missing something?

**Comment by r3c** [comment]
This is probably caused by the relative imports I'm using, which don't work anymore with Python 3 (I'm using Python 2). An easy workaround would be to use Python 2 if you have it installed, but I'll have a look at the code and see if it can be made compatible with both versions :)

**Comment by r3c** [comment]
Update: everything seems to break with Python3, from relative imports to JSON decoding, and the "2to3" tool produced a result that can't run with both Pythons 2 and 3. I'll need more time to do a proper migration, sorry about that. In the meantime I'll update package to specify it works with Python 2 only.

**Comment by laedit** [comment]
That's ok, thanks a lot for your work.

**Comment by r3c** [comment]
I just published version 0.3.1, hopefully it enables Python 3 compatibility. I havn't tested all features yet, but did some basic deployments and everything seems to be working OK :smiley:

**Comment by laedit** [comment]
Thanks, the update works with python 3. 😄 

But I have done some tests and every time the process hangs in `ntpath.py`, I have to shut it down with `ctrl+c`.

There is the logs:

``` bash
C:\test\src>creep
[1;37mINFO: Deploying to location "default"...[0m
Traceback (most recent call last):
  File "c:\users\man-p\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\man-p\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\man-p\AppData\Local\Programs\Python\Python35\Scripts\creep.exe\__main__.py", line 9, in <module>
  File "c:\users\man-p\appdata\local\programs\python\python35\lib\site-packages\creep\creep.py", line 41, in main
    args.yes):
  File "c:\users\man-p\appdata\local\programs\python\python35\lib\site-packages\creep\src\deploy.py", line 60, in execute
    if not sync (logger, base_path, definition, location, name, append_files, remove_files, rev_from, rev_to, yes):
  File "c:\users\man-p\appdata\local\programs\python\python35\lib\site-packages\creep\src\deploy.py", line 92, in sync
    source = factory.create_source (definition.source, definition.options, base_path)
  File "c:\users\man-p\appdata\local\programs\python\python35\lib\site-packages\creep\src\factory.py", line 10, in create_source
    source = source or detect (directory)
  File "c:\users\man-p\appdata\local\programs\python\python35\lib\site-packages\creep\src\factory.py", line 64, in detect
    names = path.explode (os.path.abspath (directory))
  File "c:\users\man-p\appdata\local\programs\python\python35\lib\site-packages\creep\src\path.py", line 30, in explode
    (path, tail) = os.path.split (path)
  File "c:\users\man-p\appdata\local\programs\python\python35\lib\ntpath.py", line 207, in split
    while i and p[i-1] not in seps:
KeyboardInterrupt
```

My `.creep.env` is very simple:

``` json
{
    "default": {
        "connection": "file:///../deploy"
    }
}
```

Am I missing something?
Since it seems that it is another issue, do you want me to create a new one to track it down?

**Comment by r3c** [comment]
You're not missing anything, it should have worked, but some path operation didn't work as expected when using Windows path. I just fixed that and published a new 0.3.2 version on PyPi. I'm really sorry you encountered those issues, obviously I should have prepared more tests on Windows/Python 3 configuration. Thanks a lot for the detailed bug report!

**Comment by laedit** [comment]
Wow, thanks a lot, it's working! :smile: 
If you need a Windows tester another time, let me know.

**Comment by r3c** [comment]
Great news, thanks for testing! Now that I have a working Windows setup I'll probably play a bit more with this version to fix broken colors in console output and a few other issues :smiley:
